# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/hassan-logo.png"
    alt: "Hassan Alsheikh"

### Header
header:
  logo:
    image: "assets/img/hassan-logo.png"
    alt: "Hassan Alsheikh"

### Social
social:
  - title: "Hassan Alsheikh on Twitter"
    icon: "fab fa-twitter"
    url: "https://twitter.com/HassanAlsheikh"

  - title: "Hassan Alsheikh on Instagram"
    icon: "fab fa-instagram"
    url: "https://www.instagram.com/HassanAlsheikh"

  - title: "Hassan Alsheikh on YouTube"
    icon: "fab fa-youtube"
    url: "https://www.youtube.com/@HassanAlsheikh"

  - title: "Hassan Alsheikh on LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/HassanAlsheikh/"

  - title: "Hassan Alsheikh on TikTok"
    icon: "fab fa-tiktok"
    url: "https://www.tiktok.com/@HassanAlsheikh"

### Footer
footer:
  developer: "Developed by <strong>Alsheikh Media</strong>"
  copyright: "<strong>Hassan Alsheikh</strong>. Tomorrow Is A Better Day"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "MC"
      slug: "mc"

    - name: "Photography"
      slug: "photography"

    - name: "Public Speaking"
      slug: "public-speaking"

    - name: "Podcast"
      slug: "podcast"
