name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install rbenv and ruby-build
      run: |
        sudo apt-get update
        sudo apt-get install -y rbenv
        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        source ~/.bashrc

    - name: Install Ruby
      run: |
        rbenv install 3.1.4
        rbenv global 3.1.4
        rbenv rehash
        touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

    - name: Install dependencies
      run: bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Deploy to GitHub Pages'
        git push origin main